server:
  port: 8760

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: gateway

zuul:
  routes:
    comsumer:
      id: comsumer
      path: /**
